import type { Team } from "@/types/game";

// Static map of all 32 NHL teams with colors and metadata
// Logo CDN: https://assets.nhle.com/logos/nhl/svg/{ABBREV}_light.svg
export const NHL_TEAMS: Record<string, Team> = {
  ANA: {
    id: 24,
    abbrev: "ANA",
    fullName: "Anaheim Ducks",
    shortName: "Ducks",
    city: "Anaheim",
    conference: "Western",
    division: "Pacific",
    primaryColor: "#F47A38",
    secondaryColor: "#B9975B",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/ANA_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/ANA_dark.svg",
  },
  BOS: {
    id: 6,
    abbrev: "BOS",
    fullName: "Boston Bruins",
    shortName: "Bruins",
    city: "Boston",
    conference: "Eastern",
    division: "Atlantic",
    primaryColor: "#FFB81C",
    secondaryColor: "#000000",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/BOS_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg",
  },
  BUF: {
    id: 7,
    abbrev: "BUF",
    fullName: "Buffalo Sabres",
    shortName: "Sabres",
    city: "Buffalo",
    conference: "Eastern",
    division: "Atlantic",
    primaryColor: "#002654",
    secondaryColor: "#FCB514",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/BUF_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/BUF_dark.svg",
  },
  CGY: {
    id: 20,
    abbrev: "CGY",
    fullName: "Calgary Flames",
    shortName: "Flames",
    city: "Calgary",
    conference: "Western",
    division: "Pacific",
    primaryColor: "#C8102E",
    secondaryColor: "#F1BE48",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/CGY_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/CGY_dark.svg",
  },
  CAR: {
    id: 12,
    abbrev: "CAR",
    fullName: "Carolina Hurricanes",
    shortName: "Hurricanes",
    city: "Carolina",
    conference: "Eastern",
    division: "Metropolitan",
    primaryColor: "#CC0000",
    secondaryColor: "#000000",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/CAR_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/CAR_dark.svg",
  },
  CHI: {
    id: 16,
    abbrev: "CHI",
    fullName: "Chicago Blackhawks",
    shortName: "Blackhawks",
    city: "Chicago",
    conference: "Western",
    division: "Central",
    primaryColor: "#CF0A2C",
    secondaryColor: "#000000",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/CHI_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/CHI_dark.svg",
  },
  COL: {
    id: 21,
    abbrev: "COL",
    fullName: "Colorado Avalanche",
    shortName: "Avalanche",
    city: "Colorado",
    conference: "Western",
    division: "Central",
    primaryColor: "#6F263D",
    secondaryColor: "#236192",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/COL_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/COL_dark.svg",
  },
  CBJ: {
    id: 29,
    abbrev: "CBJ",
    fullName: "Columbus Blue Jackets",
    shortName: "Blue Jackets",
    city: "Columbus",
    conference: "Eastern",
    division: "Metropolitan",
    primaryColor: "#002654",
    secondaryColor: "#CE1126",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/CBJ_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/CBJ_dark.svg",
  },
  DAL: {
    id: 25,
    abbrev: "DAL",
    fullName: "Dallas Stars",
    shortName: "Stars",
    city: "Dallas",
    conference: "Western",
    division: "Central",
    primaryColor: "#006847",
    secondaryColor: "#8F8F8C",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/DAL_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/DAL_dark.svg",
  },
  DET: {
    id: 17,
    abbrev: "DET",
    fullName: "Detroit Red Wings",
    shortName: "Red Wings",
    city: "Detroit",
    conference: "Eastern",
    division: "Atlantic",
    primaryColor: "#CE1126",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/DET_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/DET_dark.svg",
  },
  EDM: {
    id: 22,
    abbrev: "EDM",
    fullName: "Edmonton Oilers",
    shortName: "Oilers",
    city: "Edmonton",
    conference: "Western",
    division: "Pacific",
    primaryColor: "#FF4C00",
    secondaryColor: "#003087",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/EDM_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/EDM_dark.svg",
  },
  FLA: {
    id: 13,
    abbrev: "FLA",
    fullName: "Florida Panthers",
    shortName: "Panthers",
    city: "Florida",
    conference: "Eastern",
    division: "Atlantic",
    primaryColor: "#041E42",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/FLA_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/FLA_dark.svg",
  },
  LAK: {
    id: 26,
    abbrev: "LAK",
    fullName: "Los Angeles Kings",
    shortName: "Kings",
    city: "Los Angeles",
    conference: "Western",
    division: "Pacific",
    primaryColor: "#111111",
    secondaryColor: "#A2AAAD",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/LAK_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/LAK_dark.svg",
  },
  MIN: {
    id: 30,
    abbrev: "MIN",
    fullName: "Minnesota Wild",
    shortName: "Wild",
    city: "Minnesota",
    conference: "Western",
    division: "Central",
    primaryColor: "#154734",
    secondaryColor: "#A6192E",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/MIN_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/MIN_dark.svg",
  },
  MTL: {
    id: 8,
    abbrev: "MTL",
    fullName: "Montreal Canadiens",
    shortName: "Canadiens",
    city: "Montreal",
    conference: "Eastern",
    division: "Atlantic",
    primaryColor: "#AF1E2D",
    secondaryColor: "#192168",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/MTL_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg",
  },
  NSH: {
    id: 18,
    abbrev: "NSH",
    fullName: "Nashville Predators",
    shortName: "Predators",
    city: "Nashville",
    conference: "Western",
    division: "Central",
    primaryColor: "#FFB81C",
    secondaryColor: "#041E42",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/NSH_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/NSH_dark.svg",
  },
  NJD: {
    id: 1,
    abbrev: "NJD",
    fullName: "New Jersey Devils",
    shortName: "Devils",
    city: "New Jersey",
    conference: "Eastern",
    division: "Metropolitan",
    primaryColor: "#CE1126",
    secondaryColor: "#000000",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/NJD_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/NJD_dark.svg",
  },
  NYI: {
    id: 2,
    abbrev: "NYI",
    fullName: "New York Islanders",
    shortName: "Islanders",
    city: "New York",
    conference: "Eastern",
    division: "Metropolitan",
    primaryColor: "#00539B",
    secondaryColor: "#F47D30",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/NYI_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/NYI_dark.svg",
  },
  NYR: {
    id: 3,
    abbrev: "NYR",
    fullName: "New York Rangers",
    shortName: "Rangers",
    city: "New York",
    conference: "Eastern",
    division: "Metropolitan",
    primaryColor: "#0038A8",
    secondaryColor: "#CE1126",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/NYR_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/NYR_dark.svg",
  },
  OTT: {
    id: 9,
    abbrev: "OTT",
    fullName: "Ottawa Senators",
    shortName: "Senators",
    city: "Ottawa",
    conference: "Eastern",
    division: "Atlantic",
    primaryColor: "#C52032",
    secondaryColor: "#C69214",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/OTT_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/OTT_dark.svg",
  },
  PHI: {
    id: 4,
    abbrev: "PHI",
    fullName: "Philadelphia Flyers",
    shortName: "Flyers",
    city: "Philadelphia",
    conference: "Eastern",
    division: "Metropolitan",
    primaryColor: "#F74902",
    secondaryColor: "#000000",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/PHI_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/PHI_dark.svg",
  },
  PIT: {
    id: 5,
    abbrev: "PIT",
    fullName: "Pittsburgh Penguins",
    shortName: "Penguins",
    city: "Pittsburgh",
    conference: "Eastern",
    division: "Metropolitan",
    primaryColor: "#FCB514",
    secondaryColor: "#000000",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/PIT_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/PIT_dark.svg",
  },
  SEA: {
    id: 55,
    abbrev: "SEA",
    fullName: "Seattle Kraken",
    shortName: "Kraken",
    city: "Seattle",
    conference: "Western",
    division: "Pacific",
    primaryColor: "#001628",
    secondaryColor: "#99D9D9",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/SEA_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/SEA_dark.svg",
  },
  SJS: {
    id: 28,
    abbrev: "SJS",
    fullName: "San Jose Sharks",
    shortName: "Sharks",
    city: "San Jose",
    conference: "Western",
    division: "Pacific",
    primaryColor: "#006D75",
    secondaryColor: "#EA7200",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/SJS_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/SJS_dark.svg",
  },
  STL: {
    id: 19,
    abbrev: "STL",
    fullName: "St. Louis Blues",
    shortName: "Blues",
    city: "St. Louis",
    conference: "Western",
    division: "Central",
    primaryColor: "#002F87",
    secondaryColor: "#FCB514",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/STL_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/STL_dark.svg",
  },
  TBL: {
    id: 14,
    abbrev: "TBL",
    fullName: "Tampa Bay Lightning",
    shortName: "Lightning",
    city: "Tampa Bay",
    conference: "Eastern",
    division: "Atlantic",
    primaryColor: "#002868",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/TBL_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg",
  },
  TOR: {
    id: 10,
    abbrev: "TOR",
    fullName: "Toronto Maple Leafs",
    shortName: "Maple Leafs",
    city: "Toronto",
    conference: "Eastern",
    division: "Atlantic",
    primaryColor: "#00205B",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/TOR_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/TOR_dark.svg",
  },
  UTA: {
    id: 59,
    abbrev: "UTA",
    fullName: "Utah Hockey Club",
    shortName: "Hockey Club",
    city: "Utah",
    conference: "Western",
    division: "Central",
    primaryColor: "#69B3E7",
    secondaryColor: "#010101",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/UTA_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/UTA_dark.svg",
  },
  VAN: {
    id: 23,
    abbrev: "VAN",
    fullName: "Vancouver Canucks",
    shortName: "Canucks",
    city: "Vancouver",
    conference: "Western",
    division: "Pacific",
    primaryColor: "#00205B",
    secondaryColor: "#00843D",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/VAN_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/VAN_dark.svg",
  },
  VGK: {
    id: 54,
    abbrev: "VGK",
    fullName: "Vegas Golden Knights",
    shortName: "Golden Knights",
    city: "Vegas",
    conference: "Western",
    division: "Pacific",
    primaryColor: "#B4975A",
    secondaryColor: "#333F42",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/VGK_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/VGK_dark.svg",
  },
  WSH: {
    id: 15,
    abbrev: "WSH",
    fullName: "Washington Capitals",
    shortName: "Capitals",
    city: "Washington",
    conference: "Eastern",
    division: "Metropolitan",
    primaryColor: "#041E42",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/WSH_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/WSH_dark.svg",
  },
  WPG: {
    id: 52,
    abbrev: "WPG",
    fullName: "Winnipeg Jets",
    shortName: "Jets",
    city: "Winnipeg",
    conference: "Western",
    division: "Central",
    primaryColor: "#041E42",
    secondaryColor: "#AC162C",
    logoUrl: "https://assets.nhle.com/logos/nhl/svg/WPG_light.svg",
    darkLogoUrl: "https://assets.nhle.com/logos/nhl/svg/WPG_dark.svg",
  },
};

export const NHL_TEAMS_LIST = Object.values(NHL_TEAMS).sort((a, b) =>
  a.city.localeCompare(b.city)
);

export function getTeamColors(abbrev: string): {
  primaryColor: string;
  secondaryColor: string;
} {
  const team = NHL_TEAMS[abbrev.toUpperCase()];
  return {
    primaryColor: team?.primaryColor ?? "#6B7280",
    secondaryColor: team?.secondaryColor ?? "#374151",
  };
}

export function getTeam(abbrev: string): Team | undefined {
  return NHL_TEAMS[abbrev.toUpperCase()];
}
